"""update relationships 2

Revision ID: 20ba0ccc6bf5
Revises: 534a1865e0e2
Create Date: 2022-05-01 13:43:58.976659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ba0ccc6bf5'
down_revision = '534a1865e0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_authors',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    op.drop_index('ix_categories_id', table_name='categories')
    op.drop_index('ix_categories_name', table_name='categories')
    op.drop_table('author_books')
    op.drop_table('category_books')
    op.drop_table('categories')
    
    op.alter_column('authors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('books', sa.Column('title', sa.String(), nullable=False))
    op.drop_index('ix_books_name', table_name='books')
    op.drop_index('ix_books_publisher', table_name='books')
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.drop_column('books', 'name')
    op.drop_column('books', 'publisher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publisher', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.create_index('ix_books_publisher', 'books', ['publisher'], unique=False)
    op.create_index('ix_books_name', 'books', ['name'], unique=False)
    op.drop_column('books', 'title')
    op.alter_column('authors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('category_books',
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], name='category_books_book_id_fkey'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='category_books_category_id_fkey'),
    sa.PrimaryKeyConstraint('category_id', 'book_id', name='category_books_pkey')
    )
    op.create_table('author_books',
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name='author_books_author_id_fkey'),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], name='author_books_book_id_fkey'),
    sa.PrimaryKeyConstraint('author_id', 'book_id', name='author_books_pkey')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.create_index('ix_categories_id', 'categories', ['id'], unique=False)
    op.drop_table('book_authors')
    # ### end Alembic commands ###
