"""update relationships

Revision ID: 534a1865e0e2
Revises: f672f1bf7629
Create Date: 2022-05-01 12:07:21.258414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '534a1865e0e2'
down_revision = 'f672f1bf7629'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('author_books')
    #op.drop_table('category_books')
    #op.add_column('books', sa.Column('authors_id', postgresql.ARRAY(sa.ForeignKey('authors.id')), nullable=False))
    #op.add_column('books', sa.Column('categories_id', postgresql.ARRAY(sa.ForeignKey('categories.id')), nullable=False))
    #op.create_foreign_key(None, 'books', 'authors', ['authors_id'], ['id'])
    #op.create_foreign_key(None, 'books', 'categories', ['categories_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'categories_id')
    op.drop_column('books', 'authors_id')
    op.create_table('category_books',
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], name='category_books_book_id_fkey'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='category_books_category_id_fkey'),
    sa.PrimaryKeyConstraint('category_id', 'book_id', name='category_books_pkey')
    )
    op.create_table('author_books',
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name='author_books_author_id_fkey'),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], name='author_books_book_id_fkey'),
    sa.PrimaryKeyConstraint('author_id', 'book_id', name='author_books_pkey')
    )
    # ### end Alembic commands ###
