FROM python:3.8-alpine

MAINTAINER Rodrigo Santos

LABEL version="1.29.2"

RUN mkdir /authentication

WORKDIR /authentication

COPY requirements.txt /authentication/requirements.txt

RUN apk update && apk add gcc libc-dev libffi-dev python3-dev mariadb-dev		

RUN pip install --no-cache-dir -r requirements.txt;

COPY src/ /authentication

RUN chmod +x startup.sh  

EXPOSE 8000

ENTRYPOINT ["./startup.sh"]
