version: '3.7'

services:

  frontend:
    container_name: react
    build:
      context: react
      dockerfile: deploy/Dockerfile
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

