apiVersion: v1
kind: Service
metadata: 
  name: postgres-headless-svc
  namespace: egs7
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
