apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-biblify1-pvc
  namespace: egs7
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-biblify2-pvc
  namespace: egs7
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
